### ISSUE TITLE
interface conversion: interface is runtime.errorString, not string

### ISSUE THREAD

**Issue by hemantasapkota** [olebedev/go-starter-kit#35]
When trying to run after successful build, the site displays:

```
panic recover
 interface conversion: interface is runtime.errorString, not string
 stack trace 5869 bytes
 goroutine 4 [running]:
go-starter-kit/vendor/github.com/labstack/echo/middleware.Recover.func1.1.1(0xc82020a180)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/labstack/echo/middleware/recover.go:20 +0xa9
main.(*React).Handle.func1(0xc82020a180, 0xc8200141d0)
	/Users/hemantasapkota/go/src/go-starter-kit/server/react.go:56 +0xad
go-starter-kit/vendor/gopkg.in/olebedev/go-duktape%2ev2._cgoCheckPointer0(0x44b8520, 0xc82002a018, 0x0, 0x0, 0x0, 0x4491220)
	go-starter-kit/vendor/gopkg.in/olebedev/go-duktape.v2/_obj/_cgo_gotypes.go:114 +0x4d
go-starter-kit/vendor/gopkg.in/olebedev/go-duktape%2ev2.(*Context).PushPointer(0xc82002a018, 0xc82002a018)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/gopkg.in/olebedev/go-duktape.v2/api.go:1450 +0x9c
go-starter-kit/vendor/gopkg.in/olebedev/go-duktape%2ev2.(*Context).PushGoFunction(0xc82002a018, 0x4735798, 0xa)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/gopkg.in/olebedev/go-duktape.v2/duktape.go:87 +0xf1
go-starter-kit/vendor/gopkg.in/olebedev/go-duktape%2ev2.(*Context).PushGlobalGoFunction(0xc82002a018, 0x465d960, 0xa, 0x4735798, 0xc82000e301, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/gopkg.in/olebedev/go-duktape.v2/duktape.go:70 +0x1ca
go-starter-kit/vendor/gopkg.in/olebedev/go-duktape%2ev2.(*Context).PushTimers(0xc82002a018, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/gopkg.in/olebedev/go-duktape.v2/timers.go:19 +0xe2
go-starter-kit/vendor/gopkg.in/olebedev/go-duktape-fetch%2ev2.PushGlobal(0xc82002a018, 0x5908c58, 0xc820144fd0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/gopkg.in/olebedev/go-duktape-fetch.v2/fetch.go:24 +0x25
main.newReactVM(0xc82011d380, 0x16, 0x5908c58, 0xc820144fd0, 0xc82005d458)
	/Users/hemantasapkota/go/src/go-starter-kit/server/react.go:156 +0x103
main.(*onDemandPool).get(0xc82011d540, 0x47358f8)
	/Users/hemantasapkota/go/src/go-starter-kit/server/react.go:209 +0x44
main.(*React).Handle(0xc8201fc060, 0xc82020a180, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/server/react.go:61 +0x146
main.NewApp.func4.1(0xc82020a180, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/server/app.go:126 +0x293
go-starter-kit/vendor/github.com/labstack/echo.wrapHandlerFuncMW.func1.1(0xc82020a180, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/labstack/echo/echo.go:656 +0x7d
go-starter-kit/vendor/github.com/labstack/echo.wrapHandlerFuncMW.func1.1(0xc82020a180, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/labstack/echo/echo.go:656 +0x7d
go-starter-kit/vendor/github.com/labstack/echo/middleware.Recover.func1.1(0xc82020a180, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/labstack/echo/middleware/recover.go:25 +0x66
go-starter-kit/vendor/github.com/labstack/echo/middleware.Logger.func1.1(0xc82020a180, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/labstack/echo/middleware/logger.go:28 +0x12a
go-starter-kit/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc820144fd0, 0x4ca51a8, 0xc82020e000, 0xc820208000)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/labstack/echo/echo.go:542 +0x2ac
net/http.serverHandler.ServeHTTP(0xc8200b4d80, 0x4ca51a8, 0xc82020e000, 0xc820208000)
	/Users/hemantasapkota/go1.5/src/net/http/server.go:1883 +0x19e
net/http.(*conn).serve(0xc820202000)
	/Users/hemantasapkota/go1.5/src/net/http/server.go:1374 +0xc7d
created by net/http.(*Server).Serve
	/Users/hemantasapkota/go1.5/src/net/http/server.go:1941 +0x478

goroutine 1 [IO wait]:
net.runtime_pollWait(0x5909eb8, 0x72, 0x5900000)
	/Users/hemantasapkota/go1.5/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82018cdf0, 0x72, 0x0, 0x0)
	/Users/hemantasapkota/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82018cdf0, 0x0, 0x0)
	/Users/hemantasapkota/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82018cd90, 0x0, 0x5909fb0, 0xc82000a200)
	/Users/hemantasapkota/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200820d0, 0x4060f40, 0x0, 0x0)
	/Users/hemantasapkota/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200820d0, 0x0, 0x0, 0x0, 0x0)
	/Users/hemantasapkota/go1.5/src/net/http/server.go:2190 +0x41
net/http.(*Server).Serve(0xc8200b4d80, 0x5909f78, 0xc8200820d0, 0x0, 0x0)
	/Users/hemantasapkota/go1.5/src/net/http/server.go:1918 +0x129
net/http.(*Server).ListenAndServe(0xc8200b4d80, 0x0, 0x0)
	/Users/hemantasapkota/go1.5/src/net/http/server.go:1899 +0x136
go-starter-kit/vendor/github.com/labstack/echo.(*Echo).run(0xc820144fd0, 0xc8200b4d80, 0x0, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/labstack/echo/echo.go:586 +0xb0
go-starter-kit/vendor/github.com/labstack/echo.(*Echo).Run(0xc820144fd0, 0xc820192930, 0x5)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/labstack/echo/echo.go:561 +0x5e
main.(*App).Run(0xc82011d560)
	/Users/hemantasapkota/go/src/go-starter-kit/server/app.go:138 +0xb8
main.RunServer(0xc82011f0e0)
	/Users/hemantasapkota/go/src/go-starter-kit/server/main.go:37 +0x60
go-starter-kit/vendor/github.com/codegangsta/cli.Command.Run(0x4649578, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4651d80, 0xb, 0x0, ...)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/codegangsta/cli/command.go:137 +0x1081
go-starter-kit/vendor/github.com/codegangsta/cli.(*App).Run(0xc82011eea0, 0xc820086000, 0x2, 0x2, 0x0, 0x0)
	/Users/hemantasapkota/go/src/go-starter-kit/vendor/github.com/codegangsta/cli/app.go:176 +0xffa
main.Run(0xc820086000, 0x2, 0x2)
	/Users/hemantasapkota/go/src/go-starter-kit/server/main.go:28 +0xfb
main.main()
	/Users/hemantasapkota/go/src/go-starter-kit/server/main.go:10 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/hemantasapkota/go1.5/src/runtime/asm_amd64.s:1988 +0x1

```

**Comment by olebedev** [comment]
Thanks for the report. It looks like it a go-duktape issue. Could you tell me the Go version and os/arch,

**Comment by hemantasapkota** [comment]
Yep. 

`go version devel +0417872 Mon Nov 23 04:04:07 2015 +0000 darwin/amd64
`

**Comment by olebedev** [comment]
Thanks. Related issue already there https://github.com/olebedev/go-duktape/issues/34. If you still need to make go-starter-kit work please use Go 1.5.3. I'll fix it asap.

**Comment by hemantasapkota** [comment]
Thanks a lot for the fix. I just updated the master. It works!! with Go 1.6
